<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">escapeSpclChar</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsgDQpTdHJp
bmcgc2VhcmNoID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJpbnB1dFN0
cmluZyIgKTsNCmlmKHNlYXJjaCE9bnVsbCAmJiBzZWFyY2ghPSIiKXsNCglpZiAoc2VhcmNoLmNv
bnRhaW5zKCInIikgKXsNCgkNCgkgICAgc2VhcmNoID0gc2VhcmNoLnJlcGxhY2VBbGwoIiciLCAi
JyciKTsNCgkgIA0KCX0NCglpZiAoc2VhcmNoLmNvbnRhaW5zKCImIikgKXsNCgkJDQoJICAgIHNl
YXJjaCA9IHNlYXJjaC5yZXBsYWNlQWxsKCImIiwgIiZhbXA7Iik7DQoJICANCgl9DQoJaWYgKHNl
YXJjaC5jb250YWlucygiPCIpICl7DQoJCQ0KCSAgICBzZWFyY2ggPSBzZWFyY2gucmVwbGFjZUFs
bCgiPCIsICImbHQ7Iik7DQoJICANCgl9DQoJaWYgKHNlYXJjaC5jb250YWlucygiPiIpICl7DQoJ
CQ0KCSAgICBzZWFyY2ggPSBzZWFyY2gucmVwbGFjZUFsbCgiPiIsICImZ3Q7Iik7DQoJfQ0KCWlm
IChzZWFyY2guY29udGFpbnMoIiUiKSApew0KCQkJDQoJCXNlYXJjaCA9IHNlYXJjaC5yZXBsYWNl
QWxsKCIlIiwgIjslIik7DQoJICAgICANCgl9DQp9DQoNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vy
c29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsgIA0KIA0KSURhdGFVdGlsLnB1dCggcGlwZWxp
bmVDdXJzb3JfMSwgInJlcGxhY2VkU3RyaW5nIiwgc2VhcmNoKTsgIA0KcGlwZWxpbmVDdXJzb3Jf
MS5kZXN0cm95KCk7IA==</value>
</Values>
