<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">addUserToMWSRole</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURpcmVjdG9yeVNlc3Npb24gc2Vzc2lvbiA9IGNyZWF0ZUlEaXJlY3RvcnlTZXNzaW9uKCk7DQpJ
RGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOyAgDQpTdHJp
bmcgIHVzZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInVzZXJJZCIg
KTsgIA0KU3RyaW5nICByb2xlID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3Is
ICJyb2xlTmFtZSIgKTsgIA0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOyAgDQpJRGlyZWN0b3J5
UHJpbmNpcGFsIHByaW5jaXBhbFVzZXIgPSBzZXNzaW9uLmxvb2t1cFByaW5jaXBhbEJ5TmFtZSh1
c2VyLCBJRGlyZWN0b3J5UHJpbmNpcGFsLlRZUEVfVVNFUik7ICANCmlmKHByaW5jaXBhbFVzZXIg
IT0gbnVsbCl7DQoJSURpcmVjdG9yeVJvbGUgcHJpbmNpcGFsUm9sZSA9IChJRGlyZWN0b3J5Um9s
ZSkgc2Vzc2lvbi5sb29rdXBQcmluY2lwYWxCeU5hbWUocm9sZSwgSURpcmVjdG9yeVByaW5jaXBh
bC5UWVBFX1JPTEUpOw0KCXNlc3Npb24uYWRkUHJpbmNpcGFsVG9Sb2xlKHByaW5jaXBhbFVzZXIu
Z2V0SUQoKSwgcHJpbmNpcGFsUm9sZS5nZXRJRCgpKTsNCgkNCn0NCgk=</value>
</Values>
