<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">filterDocListByName</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsgDQpJRGF0
YQlkb2N1bWVudCA9IElEYXRhVXRpbC5nZXRJRGF0YSggcGlwZWxpbmVDdXJzb3IsICJpbnB1dERv
YyIgKTsNClN0cmluZyAga2V5ID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3Is
ICJrZXkiICk7ICANCklEYXRhW10gZG9jTGlzdCA9IG51bGw7DQpJRGF0YUN1cnNvciBfZGF0YWN1
cnNvciA9IGRvY3VtZW50LmdldEN1cnNvcigpIDsNCmRvY0xpc3QgPSBJRGF0YVV0aWwuZ2V0SURh
dGFBcnJheShfZGF0YWN1cnNvcixrZXkpOw0KLyp3aGlsZShfZGF0YWN1cnNvci5oYXNNb3JlRGF0
YSgpKXsNCglfZGF0YWN1cnNvci5uZXh0KCk7DQoJZG9jTGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0
YUFycmF5KF9kYXRhY3Vyc29yLGtleSk7DQp9Ki8NCg0KDQpJRGF0YUN1cnNvciBwaXBlbGluZUN1
cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7ICANCiANCklEYXRhVXRpbC5wdXQoIHBpcGVs
aW5lQ3Vyc29yXzEsICJkb2NMaXN0IiwgZG9jTGlzdCk7ICANCnBpcGVsaW5lQ3Vyc29yXzEuZGVz
dHJveSgpOyA=</value>
</Values>
