<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">removeLastOccuranceOfCharFromString</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlpblN0cmluZyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5TdHJp
bmciICk7DQpTdHJpbmcJcmVtb3ZlU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJyZW1vdmVTdHJpbmciICk7DQpwaXBlbGluZUN1cnNvci5kZXN0cm95KCk7DQoN
ClN0cmluZyBvdXRTdHJpbmc9IiI7DQppbnQgSW5kZXg9LTE7DQoNCmlmKGluU3RyaW5nICE9IG51
bGwgfHwgaW5TdHJpbmcudHJpbSgpIT0iIil7DQoNCkluZGV4PWluU3RyaW5nLmxhc3RJbmRleE9m
KHJlbW92ZVN0cmluZyk7DQppZihJbmRleD09LTEpew0KfWVsc2V7DQoJb3V0U3RyaW5nPWluU3Ry
aW5nLnN1YnN0cmluZygwLEluZGV4KTsNCn0NCn0NCg0KLy8gcGlwZWxpbmUNCklEYXRhQ3Vyc29y
IHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklEYXRhVXRpbC5wdXQo
IHBpcGVsaW5lQ3Vyc29yXzEsICJvdXRTdHJpbmciLCBvdXRTdHJpbmcgKTsNCnBpcGVsaW5lQ3Vy
c29yXzEuZGVzdHJveSgpOw==</value>
</Values>
