<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">fetchUserMWSRoles</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURpcmVjdG9yeVNlc3Npb24gc2Vzc2lvbiA9IGNyZWF0ZUlEaXJlY3RvcnlTZXNzaW9uKCk7DQpJ
RGF0YUN1cnNvciBwaXBlbGluZUN1cnNvciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOyAgDQpTdHJp
bmcgIHVzZXIgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgInVzZXJJZCIg
KTsgIA0KU3RyaW5nW10gcm9sZUxpc3QgPSBudWxsOw0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgp
OyAgDQpJRGlyZWN0b3J5UHJpbmNpcGFsIHByaW5jaXBhbFVzZXIgPSBzZXNzaW9uLmxvb2t1cFBy
aW5jaXBhbEJ5TmFtZSh1c2VyLCBJRGlyZWN0b3J5UHJpbmNpcGFsLlRZUEVfVVNFUik7ICANCmlm
KHByaW5jaXBhbFVzZXIgIT0gbnVsbCl7DQoJTGlzdDxJRGlyZWN0b3J5Um9sZT4gcm9sZXMgPSBz
ZXNzaW9uLmdldFJvbGVNZW1iZXJzaGlwKHByaW5jaXBhbFVzZXIuZ2V0SUQoKSk7DQoJcm9sZUxp
c3QgPSBuZXcgU3RyaW5nW3JvbGVzLnNpemUoKV07DQoJSXRlcmF0b3I8SURpcmVjdG9yeVJvbGU+
IGl0ZXIgPSByb2xlcy5pdGVyYXRvcigpOw0KCWludCBpPTA7DQoJd2hpbGUoaXRlci5oYXNOZXh0
KCkpew0KCQlyb2xlTGlzdFtpXSA9IGl0ZXIubmV4dCgpLmdldE5hbWUoKTsNCgkJaSsrOw0KCX0N
Cn0NCg0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNvcigp
OyAgDQogDQpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAicm9sZUxpc3QiLCByb2xl
TGlzdCApOw0KDQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsgIA==</value>
</Values>
